# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pencapp', '0002_auto_20170922_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='pencapp.Team'),
        ),
    ]
