# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pencapp', '0003_auto_20170922_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pencapp.Match')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pencapp.Team')),
            ],
        ),
    ]
